### ISSUE TITLE
Question for C# version

### ISSUE THREAD

**Issue by GuildOfCalamity** [lapo-luchini/asn1js#58] opened 2023-01-14 01:03 UTC
This isn't an issue per say, but I was wondering if anyone has converted this to C#

**Comment by lapo-luchini** [comment] 2023-01-15 16:55
C# it's a very different language than JavaScript, I'm not sure a porting makes sense.

I'm not a C# dev myself, so I'm not sure, but I know at least [Bouncy Castle](https://www.bouncycastle.org/csharp/) includes a good ASN.1 parsing library used by them internally to do crypto stuff (almost all digital signature schemes use ASN.1 DER structures).

I know nothing about it, but I see that there is also [official support from Microsoft](https://learn.microsoft.com/en-us/dotnet/api/system.formats.asn1.asndecoder?view=net-7.0).

Or are you asking more in the line of "a graphical/visual tree-based decoder" than a raw ASN.1 decoder?

PS: I'm closing as not a bug, but feel free to reply.

**Closed by lapo-luchini** 2023-01-15 16:55 UTC

**Comment by GuildOfCalamity** [comment] 2023-01-18 13:49
@lapo-luchini Thanks for the reply, I was able to convert the section I need into C# based on the original C version located here: [https://www.cs.auckland.ac.nz/~pgut001/dumpasn1.c](url)
